server:
  # 本地调试时使用
  port: 8083    
  context-path: /rpc-server
spring: 
  application:
    name: rpc-server
  profiles:
    active: online
  
access: 
  key: 3xq9IvdAtbuWf9dA
  secret: Pq7DfIOQ3pINL5C6wVD0L4ywrYTn02
